name: CI/CD Tienda Perritos - Backend

on:
  push:
    branches: [ "deploy" ]
    paths:
      - "backend/**"

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codigo
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Backend y push a ECR
      run: |
        cd backend
        docker build -t tienda-backend .
        docker tag tienda-backend:latest ${{ secrets.ECR_REPO_URL_BACKEND }}
        docker push ${{ secrets.ECR_REPO_URL_BACKEND }}

    - name: Desplegar Backend via SSM
      env:
        REGION: ${{ secrets.AWS_REGION }}
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPO: ${{ secrets.ECR_REPO_URL_BACKEND }}
        INSTANCE_ID: ${{ secrets.EC2_BACKEND_INSTANCE_ID }}
      run: |
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters commands=["aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REGISTRY","docker pull $ECR_REPO:latest","docker stop tienda-backend || true","docker rm tienda-backend || true","docker run -d --name tienda-backend -p 3001:3001 -e DB_HOST=${{ secrets.DB_HOST }} $ECR_REPO:latest"] \
          --region "$REGION"